name: CI-pipeline

# Controls when the workflow will run
on:
  # Triggers the workflow on pull request events for specified branches
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains one job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Prepare an environment
      - name: Environment setup
        run: |
          make venv

      # Compare the test and the result files
      - name: Comparison
        run: |
          source .venv/bin/activate
          python3 parse-hamnosys.py -sf test/test_source.txt -df test/hamnosys_parsed.txt -ef test/error.txt
          echo "Compare test and result files"
          python3 test/test_result_files.py -tf test/test_result.txt -rf test/hamnosys_parsed.txt

          # Check if diff.txt file exists
          FILE=test/diff.txt
          if test -f "$FILE"; then
              echo "Differences in test and result files"
              exit 1
          else
              echo "Test and result files are the same"
              exit 0
          fi

      - name: Clean
        run: |
          make venv-clean
